In [1]:
import numpy as np
import pandas as pd

In [2]:
import xgboost as xgb

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
iris = pd.read_csv("https://bit.ly/ds-iris")

In [5]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [43]:
X = iris.iloc[:,:-1]
y = iris.iloc[:,-1]

In [44]:
X_train, X_test, y_train, y_test= train_test_split(X, y,test_size=0.2, random_state=123)

In [70]:
xg_cl = xgb.XGBClassifier(objective='binary:logistic', seed=123)

In [71]:
xg_cl.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=123,
       silent=True, subsample=1)

In [72]:
xg_cl.score(X_train,y_train)

C:\Users\mohammads6\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


ValueError: continuous is not supported

In [48]:
xg_cl.score(X_test,y_test)

C:\Users\mohammads6\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


0.9666666666666667

In [52]:
xg_cl.feature_importances_

array([0.1362963 , 0.09777778, 0.41777778, 0.34814814], dtype=float32)

In [49]:
from sklearn.ensemble import RandomForestClassifier
rf_c = RandomForestClassifier()
rf_c.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [50]:
rf_c.score(X_train,y_train)

0.9916666666666667

In [51]:
rf_c.score(X_test,y_test)

0.9333333333333333

## XGBOOST

In [74]:
xg_reg = xgb.XGBRegressor(objective='reg:linear', seed=123) #,n_estimators=10

In [75]:
mtcars = pd.read_csv("https://bit.ly/ds-mtcars")

In [76]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
cars    32 non-null object
mpg     32 non-null float64
cyl     32 non-null int64
disp    32 non-null float64
hp      32 non-null int64
drat    32 non-null float64
wt      32 non-null float64
qsec    32 non-null float64
vs      32 non-null int64
am      32 non-null int64
gear    32 non-null int64
carb    32 non-null int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [77]:
X = mtcars.drop(["cars", "mpg"], axis=1)
y = mtcars.mpg

In [78]:
X.head()

cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [79]:
y.head()

0    21.0
1    21.0
2    22.8
3    21.4
4    18.7
Name: mpg, dtype: float64

In [80]:
X_train, X_test, y_train, y_test= train_test_split(X, y,test_size=0.2, random_state=123)

In [81]:
from sklearn.preprocessing import StandardScaler

In [35]:
ss = StandardScaler()

In [37]:
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)

In [63]:
X_train.head()

cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
21    8  318.0  150  2.76  3.520  16.87   0   0     3     2
11    8  275.8  180  3.07  4.070  17.40   0   0     3     3
23    8  350.0  245  3.73  3.840  15.41   0   0     3     4
18    4   75.7   52  4.93  1.615  18.52   1   1     4     2
4     8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [64]:
xg_reg.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=10,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=123,
       silent=True, subsample=1)

In [66]:
X_train.columns

Index(['cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb'], dtype='object')

In [65]:
xg_reg.feature_importances_

array([0.0625, 0.625 , 0.3125, 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    ], dtype=float32)

In [67]:
preds = xg_reg.predict(X_test)

In [68]:
preds

array([13.721188, 13.721188, 13.721188, 13.721188, 13.721188, 15.043846,
       10.232261], dtype=float32)

In [69]:
y_test

7     24.4
31    21.4
5     18.1
26    26.0
8     22.8
27    30.4
12    17.3
Name: mpg, dtype: float64

In [40]:
xg_reg.score(X_train,y_train)

-0.7449180282579941

In [41]:
X_train.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [42]:
xg_reg.score(X_test,y_test)

-4.699621737733864

In [29]:
from sklearn.ensemble import RandomForestRegressor

In [30]:
rf = RandomForestRegressor()

In [31]:
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [32]:
rf.score(X_train,y_train)

0.9624343973156672

In [33]:
rf.score(X_test,y_test)

0.6653997114657999